services:
  sqlx-cli:
    restart: "no"
    image: kawagami77/rust-sqlx-cli:latest
    working_dir: /app
    container_name: sqlx-cli
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .env:/app/.env
      - ./migrations:/app/migrations
