name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: kawagami77/rust-sqlx-cli:latest
      # -
      #   name: Update Vultr VPS Docker Service
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.VULTR_HOST }}
      #     username: ${{ secrets.VULTR_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       sh down.sh
      #       docker pull kawagami77/rust-sqlx-cli:latest
      #       docker image prune --force
      #       sh up.sh
